### ISSUE TITLE
Add Continuous Integration

### ISSUE THREAD

**Issue by petroseskinder** [bazelbuild/BUILD_file_generator#1]
@cgrushko, here's one more thing to your likely many TODO's. 

you will need to add project to http://ci.bazel.io/, and then add project status to README so that the build state displays. For example: 
<img width="143" alt="screen shot 2017-09-14 at 11 47 23 pm" src="https://user-images.githubusercontent.com/5799696/30466110-7482ff32-99a9-11e7-9b77-0fa9649910e7.png">

When a pull request is made, this will indicate whether the PR causes code to break.

**Comment by petroseskinder** [comment]
I am not sure if this is complete. States the build is unknown.

**Comment by cgrushko** [comment]
I'm told that after the next push it will get a status.

**Comment by petroseskinder** [comment]
all right. let me try with the jade --> java change.

**Comment by petroseskinder** [comment]
I'll make the pull request and we can also verify the CLA.
