### ISSUE TITLE
Update to latest rules_scala

### ISSUE THREAD

**Issue by katre** [bazelbuild/BUILD_file_generator#25]
rules_scala has fixed https://github.com/bazelbuild/rules_scala/pull/325, which is causing a failure in Bazel's CI for BUILD_file_generator: see logs at:
https://ci.bazel.io/blue/organizations/jenkins/BUILD_file_generator/detail/BUILD_file_generator/14/pipeline

**Comment by greggdonovan** [comment]
Thanks for the heads up -- PR forthcoming.

**Comment by katre** [comment]
Thanks!
