### ISSUE TITLE
Add project description and project tags

### ISSUE THREAD

**Issue by petroseskinder** [bazelbuild/BUILD_file_generator#3]
Small nit. Currently there is no project description or tag. This reduces discoverability and both are generally useful to include. More concretely, contrast buildtools and BUILD_file_generator below:

<img width="341" alt="screen shot 2017-09-15 at 1 04 12 am" src="https://user-images.githubusercontent.com/5799696/30467321-d583e3a2-99b1-11e7-9341-4b9ba650be4b.png">

<img width="692" alt="screen shot 2017-09-15 at 1 03 10 am" src="https://user-images.githubusercontent.com/5799696/30467324-da1989c6-99b1-11e7-9f35-f36a8d23ce6b.png">

A potential description could be: *"A bazel BUILD file auto generator"*
Useful tags include: *"build-tool", "bazel"*

If you plan on including support for other languages, it makes sense to leave out the java portion from the description.

**Comment by MarkusTeufelberger** [comment]
Please also document that this is limited to Java only (unless you plan to extend this to include other languages as well).

**Comment by cgrushko** [comment]
Added some stuff, lmk if you think I can improve it further.
