### ISSUE TITLE
Please move from native to Starlark rules for external git/http repositories

### ISSUE THREAD

**Issue by aehlig** [bazelbuild/BUILD_file_generator#39]
From version 0.20 onwards, bazel by default will no longer support the native http and git repositories. Please switch to the Starlark versions of those rules.
 
For more background, see
 
-  the original announcement https://groups.google.com/d/topic/bazel-discuss/dO2MHQLwJF0/discussion
 
- and the documentation of the incompatible changes https://docs.bazel.build/versions/master/skylark/backward-compatibility.html#remove-native-git-repository
 
Once migrated, please also file an issue against http://github.com/bazelbuild/continuous-integration to reenable testing of your project as a bazel downstream project.

**Comment by hlopko** [comment]
Hi all, this flag is flipped now at bazel@HEAD and will be the default behavior of Bazel 0.20. I'll disable this project on our downstream pipeline (https://buildkite.com/bazel/bazel-with-downstream-projects-bazel/builds/537#acf06c47-10e5-4fb3-8610-bf0cea34a398). Please fix quickly and create an issue at bazelbuild/continuous-integration to reenable. Keep in mind that we are now not catching unintentional breakages of this project in bazel@HEAD.

**Comment by meteorcloudy** [comment]
@greggdonovan @cgrushko Can you help fixing this?

**Comment by greggdonovan** [comment]
@meteorcloudy Sure, I'll grab this today.

**Comment by greggdonovan** [comment]
Sorry for the delay. I just posted a PR that removes the native http_archive usage and adds some other incompatibility changes and updates.

**Comment by meteorcloudy** [comment]
@greggdonovan Please ping me again when it's merged, I'll re-enable build file generator on Bazel CI job for downstream projects.

**Comment by hlopko** [comment]
Thanks Greg, let me close this issue now!

**Comment by hlopko** [comment]
Hups, I'm afraid you'll have to close it :)
